---------- QUERRYS ----------

----------- R120 ------------

SELECT * FROM jugonzalezv.VREMPLEADOS WHERE JEFE = 'Scott Pecoraro'

----------- R121 ------------

DECLARE @EMP INT
DECLARE @SUCUR VARCHAR(32)

SET @EMP = 85939845
SELECT @SUCUR = SUCURSAL_EMP FROM jugonzalezv.VREMPLEADOS WHERE CED_EMP = @EMP
SELECT * FROM jugonzalezv.VREMPLEADOS WHERE SUCURSAL_EMP = @SUCUR

----------- R122 ------------

SELECT * FROM jugonzalezv.VREMPLEADOS WHERE SUCURSAL_EMP = 'Bogota'

----------- R123 ------------

SELECT * FROM jugonzalezv.VREMPLEADOS WHERE DEP_EMP = 'comercial' AND SUCURSAL_EMP = 'Bogota'

----------- R124 ------------

DECLARE @EMP INT
DECLARE @SUCUR VARCHAR(32)
DECLARE @SUELDO INT

SET @EMP = 893423578

SELECT @SUCUR = SUCURSAL_EMP FROM jugonzalezv.VREMPLEADOS WHERE CED_EMP = @EMP
SELECT @SUELDO = SALARIO FROM jugonzalezv.VREMPLEADOS WHERE CED_EMP = @EMP

SELECT * FROM jugonzalezv.VREMPLEADOS WHERE SUCURSAL_EMP = @SUCUR AND SALARIO = @SUELDO

----------- R125 ------------

DECLARE @SUCUR VARCHAR(32)
DECLARE @DEPTO VARCHAR(32)
DECLARE @PROM INT

SET @DEPTO = 'administrativo'
SET @SUCUR = 'Bogota'


SELECT @PROM = AVG(SALARIO) FROM jugonzalezv.VREMPLEADOS WHERE SUCURSAL_EMP = @SUCUR AND DEP_EMP = @DEPTO


SELECT * FROM jugonzalezv.VREMPLEADOS WHERE SALARIO > @PROM AND SUCURSAL_EMP = @SUCUR AND DEP_EMP = @DEPTO


----------- R126 ------------

DECLARE @SUCUR VARCHAR(32)
DECLARE @PROM INT

SET @SUCUR = 'Bogota'

SELECT @PROM = AVG(SALARIO) FROM jugonzalezv.VREMPLEADOS WHERE SUCURSAL_EMP = @SUCUR

SELECT * FROM jugonzalezv.VREMPLEADOS WHERE SALARIO > @PROM AND SUCURSAL_EMP = @SUCUR


----------- R134 ------------

SELECT NOMB_EMP,AP_EMP,COMISION FROM jugonzalezv.VREMPLEADOS WHERE COMISION IS NOT NULL
